[project]
name = "poc-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "openai>=1.102.0",
    "pyannote-audio>=3.3.2",
    "python-dotenv>=1.0.0",
    "openai-whisper>=20231117",
    "torch>=2.0.0",
]
